# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Sponsorkit
      run: npm i
    - name: Update
      run: npm run build
      env:
        SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
        SPONSORKIT_GITHUB_LOGIN: Helloyunho
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: github-actions[bot]@users.noreply.github.com
        message: 'chore: update sponsors.svg'
        add: "sponsors.*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
